Add typescript types and onboarding ping
MindscapeHQ/raygun4js pull request #525
Opened 2024-04-17 01:37 UTC by Hamish-taylor

2024-04-18 04:53 UTC, Olwiba requested changes
I'm happy with the code changes here, we just need to update the type definitions to match before we can look to ship this. Nice one 🚀

2024-04-18 04:53 UTC, Olwiba commented on types/index.d.ts
> +    disablePulse?: boolean | undefined;
these types need to be updated before we can look to ship this one 👌

2024-04-18 23:41 UTC, Olwiba approved these changes
Happy with the changes 🚀

2024-05-15 01:02 UTC, PanosNB requested changes
Primary concern is we need to get the tests to pass before releasing anything. Also check some minor typos and questions please: :-)

2024-05-15 22:45 UTC, PanosNB submitted a review, later dismissed
Ok for prerelease and thus, beta-testing on our systems

2024-05-15 22:45 UTC, PanosNB commented on src/raygun.loader.js
> +  })
This is a bit ugly here, we normally put the .catch in the line. No worries for now

2024-05-16 00:07 UTC, PanosNB approved these changes
Again, all good for prerelease and soaking in our systems

2024-05-17 00:19 UTC, phillip-haydon requested changes
Couple of comments.

2024-05-17 00:19 UTC, phillip-haydon commented on CHANGELOG.md
> +## [3.1.1]
Should be 3.1.0

2024-05-17 00:19 UTC, phillip-haydon commented on CHANGELOG.md
> +### Added
Add a change log to note we have new alias option for enableRealUserMonitoring

2024-05-28 22:16 UTC, CmdrKeen commented on bower.json
> +  "version": "3.1.1",
@Hamish-taylor Update this please (as you suggested)

2024-05-28 22:16 UTC, CmdrKeen commented on package.json
> +  "version": "3.1.1",
@Hamish-taylor Update here too :)

2024-05-28 22:26 UTC, CmdrKeen submitted a review, later dismissed
Looks good to me @Hamish-taylor - just updates on the version numbers.

2024-05-29 21:41 UTC, CmdrKeen submitted a review, later dismissed

2024-05-29 22:09 UTC, JasenPalmer commented on CHANGELOG.md
> +- Added an new option for enabling Real user monitoring
```suggestion
- Added a ping to tell Raygun that raygun4js has been set up correctly. The ping is enabled by default but can be disabled using the new `sendPing` option e.g., `rg4js('sendPing', false)`. The ping contains the version of Raygun4js and which products have been enabled (CrashReporting and/or Real User Monitoring). This information will be used to help users when setting up a new application.
- Moved the typescript types into the main raygun4js repo
- Added a new option for enabling Real User Monitoring. `rg4js('enableRealUserMonitoring', true);`
```

2024-06-04 20:37 UTC, PanosNB approved these changes
Ok, follow the usual prelease/soaking process please

2024-06-16 21:12 UTC, phillip-haydon approved these changes

2024-06-16 22:00 UTC, merged